<?php

$golfCourses = [
    "carnoustie" => [
        "name" => "Carnoustie Golf Links",
        "bookingLink" => "https://booking.carnoustie.com/",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "360",
        "image" => "images/carnoustie/general/DJI_0678-Enhanced-NR.jpg",
        "courses" => [
            "Championship" => [
                "courseId" => 1,
            ],
            "Burnside" => [
                "courseId" => 3,
            ],
            "Buddon" => [
                "courseId" => 3,
            ],
        ],
    ],
    "muirfield" => [
        "name" => "Muirfield",
        "bookingLink" => "https://www.muirfield.org.uk/visitors-new/",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "395",
        "image" => "",
        "bookingSystem" => "",
    ],
    "Royal Dornoch" => [
        "name" => "Royal Dornoch",
        "bookingLink" => "https://booking.royaldornoch.com/",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "360",
        "image" => "",
    ],
    "Turnberry" => [
        "name" => "Turnberry",
        "bookingLink" =>
            "https://turnberry.booktrump.com/tee-times?propertyid=49",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "545",
        "image" => "",
    ],
    "Kingsbarns" => [
        "name" => "Kingsbarns",
        "bookingLink" => "https://www.kingsbarns.com/reservations",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "399",
        "image" => "",
    ],
    "North Berwick" => [
        "name" => "North Berwick",
        "bookingLink" =>
            "https://www.northberwickgolfclub.com/tee_booking_request_form",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "320",
        "image" => "",
    ],
    "Cabot Highlands" => [
        "name" => "Cabot Highlands",
        "bookingLink" => "https://cabothighlands.com/make-a-reservation",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "385",
        "image" => "",
    ],
    "crudenbay" => [
        "name" => "Cruden Bay",
        "bookingLink" => "https://crudenbaygolfclub.co.uk/visitors/green-fees/",
        "onlineBooking" => "No",
        "openBooking" => "Yes",
        "greenFee" => "205",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "aberdeen",
    ],
    "Trump Aberdeen" => [
        "name" => "Trump Aberdeen",
        "bookingLink" => "https://www.trumpgolfscotland.com/golf/tee-times",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "560",
        "image" => "",
    ],
    "royalaberdeen" => [
        "name" => "Royal Aberdeen",
        "bookingLink" =>
            "https://www.brsgolf.com/royalaberdeen/visitor_home.php",
        "onlineBooking" => "No",
        "openBooking" => "Yes",
        "greenFee" => "245",
        "image" => "",
    ],
    "prestwick" => [
        "name" => "Prestwick",
        "bookingLink" => "https://visitors.brsgolf.com/prestwick#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "royaltroon" => [
        "name" => "Royal Troon",
        "bookingLink" => "https://www.brsgolf.com/royaltroon/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "395",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "machrihanish" => [
        "name" => "Machrihanish",
        "bookingLink" =>
            "https://machrihanish.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "155",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "islands",
        "courseId" => 1037,
    ],
    "Gleneagles" => [
        "name" => "Gleneagles",
        "bookingLink" =>
            "https://pursuits.gleneagles.com/reservations/template/21459/?course=The+King%27s",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "375",
        "image" => "",
    ],
    "Western Gailes" => [
        "name" => "Western Gailes",
        "bookingLink" => "https://westerngailes.com/book-a-tee-time/",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "335",
        "image" => "",
    ],
    "Dumbarnie" => [
        "name" => "Dumbarnie",
        "bookingLink" => "https://visitors.brsgolf.com/dumbarnie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "350",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "fife",
    ],
    "nairngc" => [
        "name" => "Nairn",
        "bookingLink" => "https://visitors.brsgolf.com/nairngc#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "350",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "The Machrie" => [
        "name" => "The Machrie",
        "bookingLink" =>
            "https://book.rguest.eu/onecart/golf/courses/10278/TheMachrie",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "185",
        "image" => "",
    ],
    "Gullane" => [
        "name" => "Gullane",
        "bookingLink" => "https://visitors.brsgolf.com/gullane",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "325",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "eastlothian",
    ],
    "machrihanishdunes" => [
        "name" => "Machrihanish Dunes",
        "bookingLink" => "https://visitors.brsgolf.com/machrihanishdunes",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "125",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "islands",
    ],
    "Brora" => [
        "name" => "Brora",
        "bookingLink" => "https://www.broragolfclub.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "greenFee" => "180",
        "image" => "",
    ],
    "Elie" => [
        "name" => "Elie",
        "bookingLink" => "https://elie.intelligentgolf.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "160",
        "image" => "",
    ],
    "murcarlinks" => [
        "name" => "Murcar",
        "bookingLink" => "https://visitors.brsgolf.com/murcarlinks",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "195",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "aberdeen",
    ],
    "panmure" => [
        "name" => "Panmure",
        "bookingLink" => "https://visitors.brsgolf.com/panmure#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "195",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "angus",
    ],
    "Lundin Links" => [
        "name" => "Lundin Links",
        "bookingLink" => "https://visitors.brsgolf.com/lundingc#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "175",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "fife",
    ],
    "Moray" => [
        "name" => "Moray",
        "bookingLink" => "https://www.brsgolf.com/moray/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "150",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
        "courses" => [
            "Old" => [
                "courseId" => 1,
            ],
            "New" => [
                "courseId" => 3,
            ],
        ],
    ],
    "dundonald" => [
        "name" => "Dundonald",
        "bookingLink" => "https://visitors.brsgolf.com/dundonald#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "190",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "Blairgowrie" => [
        "name" => "Blairgowrie",
        "bookingLink" =>
            "https://blairgowrie.intelligentgolf.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "155",
        "image" => "",
    ],
    "Dunbar" => [
        "name" => "Dumbar",
        "bookingLink" => "https://www.dunbargolfclub.com/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "225",
        "image" => "",
    ],
    "Boat of Garten" => [
        "name" => "Boat of Garten",
        "bookingLink" =>
            "https://boatofgarten.intelligentgolf.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "115",
        "image" => "",
    ],
    "Southerness" => [
        "name" => "Southerness",
        "bookingLink" => "https://visitors.brsgolf.com/southerness#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "115",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "south",
    ],
    "Luffness" => [
        "name" => "Luffness",
        "bookingLink" => "https://www.luffnessnew.com/visitor-booking/",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "210",
        "image" => "",
    ],
    "Fraserburgh" => [
        "name" => "Fraseburgh",
        "bookingLink" =>
            "https://fraserburghgolfclub.org/Teebooking/SearchClubDay.aspx",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "150",
        "image" => "",
    ],
    "glasgow" => [
        "name" => "Glasgow Gailes",
        "bookingLink" => "https://www.brsgolf.com/glasgow/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "180",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "Spey Valley" => [
        "name" => "Spey Valley",
        "bookingLink" =>
            "https://macdonald-hotels-spey-valley-championship.book.teeitup.com/",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "330",
        "image" => "",
    ],
    "montrosegolflinks" => [
        "name" => "Montrose",
        "bookingLink" =>
            "https://visitors.brsgolf.com/montrosegolflinks#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "angus",
        "courses" => [
            "1562" => [
                "courseId" => 1,
            ],
            "Broomfield" => [
                "courseId" => 3,
            ],
        ],
    ],
    "Askernish" => [
        "name" => "Askernish",
        "bookingLink" =>
            "https://www.askernishgolfclub.com/Teebooking/SearchClubDay.aspx",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
    ],
    "Scotscraig" => [
        "name" => "Scotscraig",
        "bookingLink" => "https://www.scotscraiggolfclub.com/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
    ],
    "levenlinks" => [
        "name" => "Leven",
        "bookingLink" => "https://visitors.brsgolf.com/levenlinks",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "leven",
    ],
    "irvine" => [
        "name" => "Irvine",
        "bookingLink" => "https://visitors.brsgolf.com/irvine#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "ladybank" => [
        "name" => "Ladybank",
        "bookingLink" => "https://visitors.brsgolf.com/ladybank#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "fife",
    ],
    "prestwickstnicholas" => [
        "name" => "Prestwick St Nicholas",
        "bookingLink" => "https://visitors.brsgolf.com/prestwickstnicholas",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "westkilbride" => [
        "name" => "West Kilbride",
        "bookingLink" => "https://visitors.brsgolf.com/westkilbride#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "ayrshire",
    ],
    "Longniddry" => [
        "name" => "Longniddry",
        "bookingLink" => "https://www.longniddrygolfclub.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
    ],
    "golspie" => [
        "name" => "Golspie",
        "bookingLink" => "https://visitors.brsgolf.com/golspie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "Kilspindie" => [
        "name" => "Kilspindie",
        "bookingLink" => "https://www.kilspindiegolfclub.co.uk/visitorbooking/",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "330",
        "image" => "",
    ],
    "monifieth" => [
        "name" => "Monifieth",
        "bookingLink" => "https://visitors.brsgolf.com/monifieth#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "angus",
        "courses" => [
            "Medal" => [
                "courseId" => 1,
            ],
            "Ashludie" => [
                "courseId" => 3,
            ],
        ],
    ],
    "Crail" => [
        "name" => "Crail",
        "bookingLink" =>
            "https://eu.cps.golf/CrailNEWv3/(S(0stz324rkgdoc0crajs2jqhy))/Home/nIndex?CourseId=19,18",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "330",
        "image" => "",
    ],
    "nairndunbargolf" => [
        "name" => "Nairn Dunbar",
        "bookingLink" =>
            "https://visitors.brsgolf.com/nairndunbargolf#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "No",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "peterhead" => [
        "name" => "Peterhead",
        "bookingLink" => "https://visitors.brsgolf.com/peterhead",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "aberdeen",
    ],
    "downfield" => [
        "name" => "Downfield",
        "bookingLink" => "https://visitors.brsgolf.com/downfield",
        "onlineBooking" => "No",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "angus",
        "courseId" => 531,
    ],
    "lanark" => [
        "name" => "Lanark",
        "bookingLink" => "https://visitors.brsgolf.com/lanark",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "south",
    ],
    "fortrose" => [
        "name" => "Fortrose and Rosemarkie",
        "bookingLink" => "https://www.brsgolf.com/fortrose/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "pitlochry" => [
        "name" => "Pitlochry",
        "bookingLink" => "https://visitors.brsgolf.com/pitlochry",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "Kilmarnock Barassie" => [
        "name" => "Kilmarnock Barassie",
        "bookingLink" => "https://www.kbgc.co.uk/visitor-booking-form",
        "onlineBooking" => "No",
        "openBooking" => "No",
        "greenFee" => "330",
        "image" => "",
    ],
    "eastrenfrewshire" => [
        "name" => "East Renfrewshire",
        "bookingLink" =>
            "https://visitors.brsgolf.com/eastrenfrewshire#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "south",
    ],
    "shiskine" => [
        "name" => "Shiskine",
        "bookingLink" => "https://visitors.brsgolf.com/shiskine",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "islands",
    ],
    "tain" => [
        "name" => "Tain",
        "bookingLink" => "https://tain.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "highlands",
        "courseId" => 753,
    ],
    "aberdour" => [
        "name" => "Aberdour",
        "bookingLink" => "https://www.brsgolf.com/aberdour/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "fife",
    ],
    "alford" => [
        "name" => "Alford",
        "bookingLink" => "https://www.brsgolf.com/alford/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "aberdeen",
    ],
    "balbirniepark" => [
        "name" => "balbirniepark",
        "bookingLink" =>
            "https://www.brsgolf.com/balbirniepark/visitor_home.php",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "330",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "islands",
    ],
    "aboyne" => [
        "name" => "Aboyne",
        "bookingLink" => "https://visitors.brsgolf.com/aboyne#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "alyth" => [
        "name" => "Alyth",
        "bookingLink" => "https://visitors.brsgolf.com/alyth#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "auchterarder" => [
        "name" => "Auchterarder",
        "bookingLink" => "https://visitors.brsgolf.com/auchterarder#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "auchterderran" => [
        "name" => "Auchterderran",
        "bookingLink" => "https://visitors.brsgolf.com/auchterderran#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "baberton" => [
        "name" => "Baberton",
        "bookingLink" => "https://visitors.brsgolf.com/baberton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "ballater" => [
        "name" => "Ballater",
        "bookingLink" => "https://visitors.brsgolf.com/ballater#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "ballindalloch" => [
        "name" => "Ballindalloch",
        "bookingLink" => "https://visitors.brsgolf.com/ballindalloch#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "ballumbie" => [
        "name" => "Ballumbie",
        "bookingLink" => "https://visitors.brsgolf.com/ballumbie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "balmore" => [
        "name" => "Balmore",
        "bookingLink" => "https://visitors.brsgolf.com/balmore#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "banchory" => [
        "name" => "Banchory",
        "bookingLink" => "https://visitors.brsgolf.com/banchory#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "blairatholl" => [
        "name" => "Blairatholl",
        "bookingLink" => "https://visitors.brsgolf.com/blairatholl#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "bonnyton" => [
        "name" => "Bonnyton",
        "bookingLink" => "https://visitors.brsgolf.com/bonnyton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "bothwellcastle" => [
        "name" => "Bothwellcastle",
        "bookingLink" =>
            "https://visitors.brsgolf.com/bothwellcastle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "braehead" => [
        "name" => "Braehead",
        "bookingLink" => "https://visitors.brsgolf.com/braehead#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "brechin" => [
        "name" => "Brechin",
        "bookingLink" => "https://visitors.brsgolf.com/brechin#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "bridgeofallan" => [
        "name" => "Bridgeofallan",
        "bookingLink" => "https://visitors.brsgolf.com/bridgeofallan#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "brodick" => [
        "name" => "Brodick",
        "bookingLink" => "https://visitors.brsgolf.com/brodick#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "buckpool" => [
        "name" => "Buckpool",
        "bookingLink" => "https://visitors.brsgolf.com/buckpool#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "burntisland" => [
        "name" => "Burntisland",
        "bookingLink" => "https://visitors.brsgolf.com/burntisland#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "caldwell" => [
        "name" => "Caldwell",
        "bookingLink" => "https://visitors.brsgolf.com/caldwell#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "callander" => [
        "name" => "Callander",
        "bookingLink" => "https://visitors.brsgolf.com/callander#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "canmore" => [
        "name" => "Canmore",
        "bookingLink" => "https://visitors.brsgolf.com/canmore#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "cardrona" => [
        "name" => "Cardrona",
        "bookingLink" => "https://visitors.brsgolf.com/cardrona#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "carluke" => [
        "name" => "Carluke",
        "bookingLink" => "https://visitors.brsgolf.com/carluke#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "carnwath" => [
        "name" => "Carnwath",
        "bookingLink" => "https://visitors.brsgolf.com/carnwath#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "castlepark" => [
        "name" => "Castlepark",
        "bookingLink" => "https://visitors.brsgolf.com/castlepark#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "clober" => [
        "name" => "Clober",
        "bookingLink" => "https://visitors.brsgolf.com/clober#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "cowdenbeath" => [
        "name" => "Cowdenbeath",
        "bookingLink" => "https://visitors.brsgolf.com/cowdenbeath#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "forfar" => [
        "name" => "Forfar",
        "bookingLink" => "https://visitors.brsgolf.com/forfar#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kirriemuir" => [
        "name" => "Kirriemuir",
        "bookingLink" => "https://visitors.brsgolf.com/kirriemuir#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "cowglen" => [
        "name" => "Cowglen",
        "bookingLink" => "https://visitors.brsgolf.com/cowglen#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "crowwood" => [
        "name" => "Crowwood",
        "bookingLink" => "https://visitors.brsgolf.com/crowwood#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "cupar" => [
        "name" => "Cupar",
        "bookingLink" => "https://visitors.brsgolf.com/cupar#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dalmahoy" => [
        "name" => "Dalmahoy",
        "bookingLink" => "https://visitors.brsgolf.com/dalmahoy#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dougalston" => [
        "name" => "Dougalston",
        "bookingLink" => "https://visitors.brsgolf.com/dougalston#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "drumoig" => [
        "name" => "Drumoig",
        "bookingLink" => "https://visitors.brsgolf.com/drumoig#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "drumpellier" => [
        "name" => "Drumpellier",
        "bookingLink" => "https://visitors.brsgolf.com/drumpellier#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dufftown" => [
        "name" => "Dufftown",
        "bookingLink" => "https://visitors.brsgolf.com/dufftown#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dumbarton" => [
        "name" => "Dumbarton",
        "bookingLink" => "https://visitors.brsgolf.com/dumbarton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dunblanenew" => [
        "name" => "Dunblanenew",
        "bookingLink" => "https://visitors.brsgolf.com/dunblanenew#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "roxburghe" => [
        "name" => "Roxburghe",
        "bookingLink" => "https://visitors.brsgolf.com/roxburghe#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "balbirniepark" => [
        "name" => "Balbirniepark",
        "bookingLink" => "https://visitors.brsgolf.com/balbirniepark#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "ballindalloch" => [
        "name" => "Ballindalloch",
        "bookingLink" => "https://visitors.brsgolf.com/ballindalloch#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "cameronhouse" => [
        "name" => "Cameronhouse",
        "bookingLink" => "https://visitors.brsgolf.com/cameronhouse#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "clydebankdistrict" => [
        "name" => "Clydebankdistrict",
        "bookingLink" =>
            "https://visitors.brsgolf.com/clydebankdistrict#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dumbarton" => [
        "name" => "Dumbarton",
        "bookingLink" => "https://visitors.brsgolf.com/dumbarton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "duns" => [
        "name" => "Duns",
        "bookingLink" => "https://visitors.brsgolf.com/duns#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dunfermline" => [
        "name" => "Dunfermline",
        "bookingLink" => "https://visitors.brsgolf.com/dunfermline#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dumfriesandcounty" => [
        "name" => "Dumfriesandcounty",
        "bookingLink" =>
            "https://visitors.brsgolf.com/dumfriesandcounty#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dumfriesandgalloway" => [
        "name" => "Dumfriesandgalloway",
        "bookingLink" =>
            "https://visitors.brsgolf.com/dumfriesandgalloway#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "eastkilbride" => [
        "name" => "Eastkilbride",
        "bookingLink" => "https://visitors.brsgolf.com/eastkilbride#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "eastermoffat" => [
        "name" => "Eastermoffat",
        "bookingLink" => "https://visitors.brsgolf.com/eastermoffat#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "edzell" => [
        "name" => "Edzell",
        "bookingLink" => "https://visitors.brsgolf.com/edzell#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "elderslie" => [
        "name" => "Elderslie",
        "bookingLink" => "https://visitors.brsgolf.com/elderslie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "elgin" => [
        "name" => "Elgin",
        "bookingLink" => "https://visitors.brsgolf.com/elgin#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "eyemouth" => [
        "name" => "Eyemouth",
        "bookingLink" => "https://visitors.brsgolf.com/eyemouth#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "falkirk" => [
        "name" => "Falkirk",
        "bookingLink" => "https://visitors.brsgolf.com/falkirk#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "falkirktryst" => [
        "name" => "Falkirktryst",
        "bookingLink" => "https://visitors.brsgolf.com/falkirktryst#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "fereneze" => [
        "name" => "Fereneze",
        "bookingLink" => "https://visitors.brsgolf.com/fereneze#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "forres" => [
        "name" => "Forres",
        "bookingLink" => "https://visitors.brsgolf.com/forres#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "glenbervie" => [
        "name" => "Glenbervie",
        "bookingLink" => "https://visitors.brsgolf.com/glenbervie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "glenrothes" => [
        "name" => "Glenrothes",
        "bookingLink" => "https://visitors.brsgolf.com/glenrothes#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "haddington" => [
        "name" => "Haddington",
        "bookingLink" => "https://visitors.brsgolf.com/haddington#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "haggscastle" => [
        "name" => "Haggscastle",
        "bookingLink" => "https://visitors.brsgolf.com/haggscastle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "hayston" => [
        "name" => "Hayston",
        "bookingLink" => "https://visitors.brsgolf.com/hayston#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "hazlehead" => [
        "name" => "Hazlehead",
        "bookingLink" => "https://visitors.brsgolf.com/hazlehead#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "helensburgh" => [
        "name" => "Helensburgh",
        "bookingLink" => "https://visitors.brsgolf.com/helensburgh#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "hirsel" => [
        "name" => "Hirsel",
        "bookingLink" => "https://visitors.brsgolf.com/hirsel#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "inchmarlo" => [
        "name" => "Inchmarlo",
        "bookingLink" => "https://visitors.brsgolf.com/inchmarlo#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "innerleithen" => [
        "name" => "Innerleithen",
        "bookingLink" => "https://visitors.brsgolf.com/innerleithen#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "insch" => [
        "name" => "Insch",
        "bookingLink" => "https://visitors.brsgolf.com/insch#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "inverness" => [
        "name" => "Inverness",
        "bookingLink" => "https://visitors.brsgolf.com/inverness#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "inverurie" => [
        "name" => "Inverurie",
        "bookingLink" => "https://visitors.brsgolf.com/inverurie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "jedburgh" => [
        "name" => "Jedburgh",
        "bookingLink" => "https://visitors.brsgolf.com/jedburgh#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kilsythlennox" => [
        "name" => "Kilsythlennox",
        "bookingLink" => "https://visitors.brsgolf.com/kilsythlennox#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kinghorn" => [
        "name" => "Kinghorn",
        "bookingLink" => "https://visitors.brsgolf.com/kinghorn#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kingussie" => [
        "name" => "Kingussie",
        "bookingLink" => "https://visitors.brsgolf.com/kingussie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kinross" => [
        "name" => "Kinross",
        "bookingLink" => "https://visitors.brsgolf.com/kinross#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kintore" => [
        "name" => "Kintore",
        "bookingLink" => "https://visitors.brsgolf.com/kintore#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kirkhill" => [
        "name" => "Kirkhill",
        "bookingLink" => "https://visitors.brsgolf.com/kirkhill#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "lamlash" => [
        "name" => "Lamlash",
        "bookingLink" => "https://visitors.brsgolf.com/lamlash#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "lanark" => [
        "name" => "Lanark",
        "bookingLink" => "https://visitors.brsgolf.com/lanark#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "linlithgow" => [
        "name" => "Linlithgow",
        "bookingLink" => "https://visitors.brsgolf.com/linlithgow#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "lochgelly" => [
        "name" => "Lochgelly",
        "bookingLink" => "https://visitors.brsgolf.com/lochgelly#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "lochoremeadows" => [
        "name" => "Lochoremeadows",
        "bookingLink" =>
            "https://visitors.brsgolf.com/lochoremeadows#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "lochwinnoch" => [
        "name" => "Lochwinnoch",
        "bookingLink" => "https://visitors.brsgolf.com/lochwinnoch#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "mcdonald" => [
        "name" => "Mcdonald",
        "bookingLink" => "https://visitors.brsgolf.com/mcdonald#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "mearnscastle" => [
        "name" => "Mearnscastle",
        "bookingLink" => "https://visitors.brsgolf.com/mearnscastle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "merchantsofedinburgh" => [
        "name" => "Merchantsofedinburgh",
        "bookingLink" =>
            "https://visitors.brsgolf.com/merchantsofedinburgh#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "milngavie" => [
        "name" => "Milngavie",
        "bookingLink" => "https://visitors.brsgolf.com/milngavie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "minto" => [
        "name" => "Minto",
        "bookingLink" => "https://visitors.brsgolf.com/minto#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "muckhart" => [
        "name" => "Muckhart",
        "bookingLink" => "https://visitors.brsgolf.com/muckhart#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "muiroford" => [
        "name" => "Muiroford",
        "bookingLink" => "https://visitors.brsgolf.com/muiroford#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "musselburgh" => [
        "name" => "Musselburgh",
        "bookingLink" => "https://visitors.brsgolf.com/musselburgh#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "newbattle" => [
        "name" => "Newbattle",
        "bookingLink" => "https://visitors.brsgolf.com/newbattle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "newtonmore" => [
        "name" => "Newtonmore",
        "bookingLink" => "https://visitors.brsgolf.com/newtonmore#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "niddrycastle" => [
        "name" => "Niddrycastle",
        "bookingLink" => "https://visitors.brsgolf.com/niddrycastle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "northinch" => [
        "name" => "Northinch",
        "bookingLink" => "https://visitors.brsgolf.com/northinch#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "oldmeldrum" => [
        "name" => "Oldmeldrum",
        "bookingLink" => "https://visitors.brsgolf.com/oldmeldrum#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "peebles" => [
        "name" => "Peebles",
        "bookingLink" => "https://visitors.brsgolf.com/peebles#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "pitreavie" => [
        "name" => "Pitreavie",
        "bookingLink" => "https://visitors.brsgolf.com/pitreavie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "portlethen" => [
        "name" => "Portlethen",
        "bookingLink" => "https://visitors.brsgolf.com/portlethen#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "portpatrick" => [
        "name" => "Portpatrick",
        "bookingLink" => "https://visitors.brsgolf.com/portpatrick#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "powfoot" => [
        "name" => "Powfoot",
        "bookingLink" => "https://visitors.brsgolf.com/powfoot#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "pumpherston" => [
        "name" => "Pumpherston",
        "bookingLink" => "https://visitors.brsgolf.com/pumpherston#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "royalaberdeen" => [
        "name" => "Royalaberdeen",
        "bookingLink" => "https://visitors.brsgolf.com/royalaberdeen#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "royalmusselburgh" => [
        "name" => "Royalmusselburgh",
        "bookingLink" =>
            "https://visitors.brsgolf.com/royalmusselburgh#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "scoonie" => [
        "name" => "Scoonie",
        "bookingLink" => "https://visitors.brsgolf.com/scoonie#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "shotts" => [
        "name" => "Shotts",
        "bookingLink" => "https://visitors.brsgolf.com/shotts#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "southerness" => [
        "name" => "Southerness",
        "bookingLink" => "https://visitors.brsgolf.com/southerness#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "stmichaels" => [
        "name" => "Stmichaels",
        "bookingLink" => "https://visitors.brsgolf.com/stmichaels#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "stirling" => [
        "name" => "Stirling",
        "bookingLink" => "https://visitors.brsgolf.com/stirling#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "stonehaven" => [
        "name" => "Stonehaven",
        "bookingLink" => "https://visitors.brsgolf.com/stonehaven#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "stranraer" => [
        "name" => "Stranraer",
        "bookingLink" => "https://visitors.brsgolf.com/stranraer#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "strathendrick" => [
        "name" => "Strathendrick",
        "bookingLink" => "https://visitors.brsgolf.com/strathendrick#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "strathmore" => [
        "name" => "Strathmore",
        "bookingLink" => "https://visitors.brsgolf.com/strathmore#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "swanston" => [
        "name" => "Swanston",
        "bookingLink" => "https://visitors.brsgolf.com/swanston#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "swanstontemplar" => [
        "name" => "Swanstontemplar",
        "bookingLink" =>
            "https://visitors.brsgolf.com/swanstontemplar#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "tarland" => [
        "name" => "Tarland",
        "bookingLink" => "https://visitors.brsgolf.com/tarland#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "thornhill" => [
        "name" => "Thornhill",
        "bookingLink" => "https://visitors.brsgolf.com/thornhill#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "thornton" => [
        "name" => "Thornton",
        "bookingLink" => "https://visitors.brsgolf.com/thornton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "torphins" => [
        "name" => "Torphins",
        "bookingLink" => "https://visitors.brsgolf.com/torphins#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "tulliallan" => [
        "name" => "Tulliallan",
        "bookingLink" => "https://visitors.brsgolf.com/tulliallan#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "turriff" => [
        "name" => "Turriff",
        "bookingLink" => "https://visitors.brsgolf.com/turriff#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "uphall" => [
        "name" => "Uphall",
        "bookingLink" => "https://visitors.brsgolf.com/uphall#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "westkilbride" => [
        "name" => "Westkilbride",
        "bookingLink" => "https://visitors.brsgolf.com/westkilbride#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "westlinton" => [
        "name" => "Westlinton",
        "bookingLink" => "https://visitors.brsgolf.com/westlinton#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "westerngailes" => [
        "name" => "Westerngailes",
        "bookingLink" => "https://visitors.brsgolf.com/westerngailes#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "westhill" => [
        "name" => "Westhill",
        "bookingLink" => "https://visitors.brsgolf.com/westhill#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "windyhill" => [
        "name" => "Windyhill",
        "bookingLink" => "https://visitors.brsgolf.com/windyhill#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "wishaw" => [
        "name" => "Wishaw",
        "bookingLink" => "https://visitors.brsgolf.com/wishaw#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "grantownonspey" => [
        "name" => "Grantownonspey",
        "bookingLink" =>
            "https://visitors.brsgolf.com/grantownonspey#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kingarrockhickory" => [
        "name" => "Kingarrockhickory",
        "bookingLink" =>
            "https://visitors.brsgolf.com/kingarrockhickory#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "oatridge-alsoknownasbinny" => [
        "name" => "Oatridge-alsoknownasbinny",
        "bookingLink" =>
            "https://visitors.brsgolf.com/oatridge-alsoknownasbinny#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dunkeldbirnam" => [
        "name" => "Dunkeldbirnam",
        "bookingLink" => "https://visitors.brsgolf.com/dunkeldbirnam#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "dunnikier" => [
        "name" => "Dunnikier",
        "bookingLink" => "https://visitors.brsgolf.com/dunnikier#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "giffordgc" => [
        "name" => "Giffordgc",
        "bookingLink" => "https://visitors.brsgolf.com/giffordgc#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kemnay" => [
        "name" => "Kemnay",
        "bookingLink" => "https://visitors.brsgolf.com/kemnay#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "newburghonythan" => [
        "name" => "Newburghonythan",
        "bookingLink" =>
            "https://visitors.brsgolf.com/newburghonythan#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "oldranfurly" => [
        "name" => "Oldranfurly",
        "bookingLink" => "https://visitors.brsgolf.com/oldranfurly#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "portpatrick" => [
        "name" => "Portpatrick",
        "bookingLink" => "https://visitors.brsgolf.com/portpatrick#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "rowallancastle" => [
        "name" => "Rowallancastle",
        "bookingLink" =>
            "https://visitors.brsgolf.com/rowallancastle#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "",
    ],
    "kings" => [
        "name" => "Kings",
        "bookingLink" => "https://kings.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 272,
    ],
    "alloa" => [
        "name" => "Alloa",
        "bookingLink" => "https://alloa.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1350,
    ],
    "bishopbriggs" => [
        "name" => "Bishopbriggs",
        "bookingLink" =>
            "https://bishopbriggs.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1024,
    ],
    "broomieknowe" => [
        "name" => "Broomieknowe",
        "bookingLink" =>
            "https://broomieknowe.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1026,
    ],
    "buchanancastle" => [
        "name" => "Buchanancastle",
        "bookingLink" =>
            "https://buchanancastle.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1300,
    ],
    "cawder" => [
        "name" => "Cawder",
        "bookingLink" => "https://cawder.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1076,
    ],
    "craibstone" => [
        "name" => "Craibstone",
        "bookingLink" => "https://craibstone.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 0,
    ],
    "cullenlinks" => [
        "name" => "Cullenlinks",
        "bookingLink" => "https://cullenlinks.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 520,
    ],
    "deeside" => [
        "name" => "Deeside",
        "bookingLink" => "https://deeside.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 0,
    ],
    "duffhouseroyal" => [
        "name" => "Duffhouseroyal",
        "bookingLink" =>
            "https://duffhouseroyal.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 535,
    ],
    "dullatur" => [
        "name" => "Dullatur",
        "bookingLink" => "https://dullatur.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1937,
    ],
    "dundasparks" => [
        "name" => "Dundasparks",
        "bookingLink" => "https://dundasparks.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 299,
    ],
    "erskine" => [
        "name" => "Erskine",
        "bookingLink" => "https://erskine.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 392,
    ],
    "fortwilliam" => [
        "name" => "Fort William",
        "bookingLink" => "https://fortwilliam.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 2312,
    ],
    "gandkgc" => [
        "name" => "Gandkgc",
        "bookingLink" => "https://gandkgc.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 2312,
    ],
    "gogarburn" => [
        "name" => "Gogarburn",
        "bookingLink" => "https://gogarburn.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1908,
    ],
    "greenburn" => [
        "name" => "Greenburn",
        "bookingLink" => "https://greenburn.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1765,
    ],
    "harburn" => [
        "name" => "Harburn",
        "bookingLink" => "https://harburn.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 93,
    ],
    "huntly" => [
        "name" => "Huntly",
        "bookingLink" => "https://huntly.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1743,
    ],
    "kelso" => [
        "name" => "Kelso",
        "bookingLink" => "https://kelso.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1322,
    ],
    "largs" => [
        "name" => "Largs",
        "bookingLink" => "https://largs.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1284,
    ],
    "loudoungowf" => [
        "name" => "Loudoungowf",
        "bookingLink" => "https://loudoungowf.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 132,
    ],
    "maverston" => [
        "name" => "Maverston",
        "bookingLink" => "https://maverston.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 4151,
    ],
    "newmachar" => [
        "name" => "Newmachar",
        "bookingLink" => "https://newmachar.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1357,
    ],
    "prestwickstcuthbert" => [
        "name" => "Prestwickstcuthbert",
        "bookingLink" =>
            "https://prestwickstcuthbert.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1303,
    ],
    "torwoodlee" => [
        "name" => "Torwoodlee",
        "bookingLink" => "https://torwoodlee.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 2894,
    ],
    "westlothian" => [
        "name" => "West Lothian",
        "bookingLink" => "https://westlothian.hub.clubv1.com/Visitors/TeeSheet",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 1623,
    ],
    "ralston" => [
        "name" => "Ralston",
        "bookingLink" =>
            "https://www.howdidido.com/Directory/OpenCompetitions/686",
        "onlineBooking" => "No",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "",
        "courseId" => 686,
    ],
    "speybay" => [
        "name" => "Spey Bay",
        "bookingLink" => "https://visitors.brsgolf.com/speybay#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "205",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "highlands",
    ],
    "mortonhall" => [
        "name" => "Mortonhall",
        "bookingLink" =>
            "https://www.howdidido.com/Directory/OpenCompetitions/3007",
        "onlineBooking" => "No",
        "openBooking" => "Yes",
        "greenFee" => "340",
        "image" => "",
        "bookingSystem" => "clubv1",
        "region" => "edinburgh",
        "courseId" => 3007,
    ],
    "turnhouse" => [
        "name" => "Turnhouse",
        "bookingLink" => "https://visitors.brsgolf.com/turnhouse#/course/1",
        "onlineBooking" => "Yes",
        "openBooking" => "Yes",
        "greenFee" => "205",
        "image" => "",
        "bookingSystem" => "brs",
        "region" => "edinburgh",
    ],
];

$masters = [
    "strathmore",
    "harburn",
    "golspie",
    "lanark",
    "stonehaven",
    "burntisland",
    "largs",
    "broomieknowe",
    "inverurie",
    "pumpherston",
    "cameronhouse",
    "elgin",
    "ralston",
    "kirriemuir",
    "kirkhill",
    "longniddry",
    "dunfermline",
    "buchanancastle",
    "muckhart",
    "dumfriesandgalloway",
    "cawder",
    "levenlinks",
    "elderslie",
    "royalmusselburgh",
    "brechin",
    "bishopbriggs",
    "erskine",
    "roxburghe",
    "speybay",
    "carnwath",
    "ballochmyle",
    "southerness",
    "clober",
    "nairn",
    "dunblanenew",
    "peterhead",
    "crudenbay",
    "newmachar",
    "turnhouse",
    "alyth",
    "downfield",
    "auchterarder",
    "haggscastle",
    "deeside",
    "eastren",
    "baberton",
];

uksort($golfCourses, function ($a, $b) {
    return strcasecmp($a, $b); // Compare keys ignoring case
});

function get_courses_for_area($region, $courseList)
{
    foreach ($courseList as $courseName => $courseInfo) {
        if (isset($courseInfo["region"]) && $courseInfo["region"] == $region) {
            $newArray[$courseName] = $courseInfo;
        }
    }

    return $newArray;
}

function get_courses_from_array($coursesToFind, $courseList)
{
    foreach ($courseList as $courseName => $courseInfo) {
        if (in_array($courseName, $coursesToFind)) {
            $newArray[$courseName] = $courseInfo;
        }
    }

    return $newArray;
}

function build_select_box($region, $label)
{
    $options = "";

    $count = 0;

    foreach ($region as $key => $properties) {
        if (isset($properties["bookingSystem"])) {
            $count++;

            if (isset($properties["courses"])) {
                foreach ($properties["courses"] as $name => $course) {
                    $options .= "<option value='{$key}' data-onlineBooking={$properties["onlineBooking"]} data-bookingSystem={$properties["bookingSystem"]} data-courseId={$course["courseId"]} data-openBooking={$properties["openBooking"]}>{$properties["name"]} - $name</option>";
                }
            } else {
                $courseId = "";

                if (isset($properties["courseId"])) {
                    $courseId = " data-courseId={$properties["courseId"]}";
                }

                $options .= "<option value='{$key}' data-onlineBooking={$properties["onlineBooking"]} data-bookingSystem={$properties["bookingSystem"]}$courseId data-openBooking={$properties["openBooking"]}>{$properties["name"]}</option>";
            }
        }
    }

    // echo "$count <br />";

    return "<select multiple='multiple' id='dropDown" .
        str_replace(" ", "", $label) .
        "' style='height:200px'>$options</select>";
}
